#!/usr/bin/env python3
"""Generate trig_lut.h: a 256-entry Q16.16 sine table for firmware movement math.

cos(x) is derived from the same table via a quarter-phase (64-entry) index
offset, same trick dda_core.sv uses in RTL via $sin/$cos — this just gives
the CPU an equivalent table since it has no hardware trig unit.
"""
import math

N = 256
Q = 65536

with open("trig_lut.h", "w") as f:
    f.write("#pragma once\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"// {N}-entry Q16.16 sine table, one period over 2*pi.\n")
    f.write("// Generated by gen_trig_lut.py — do not hand-edit.\n")
    f.write(f"#define TRIG_LUT_N {N}\n\n")
    f.write("static const int32_t sin_lut[TRIG_LUT_N] = {\n")
    for i in range(N):
        v = round(math.sin(2.0 * math.pi * i / N) * Q)
        f.write(f"    {v},\n")
    f.write("};\n")

print(f"Wrote trig_lut.h ({N} entries)")
