#!/usr/bin/env python3
"""Emit the FPGA demo memory images and layer program (Phase 7).

The demo runs the CIFAR-shaped 5-layer program (32x32x3 -> 1x1x4, stride-2
pad-1 conv per layer) on a fixed seeded image with seeded random weights
(architecture bring-up; trained weights are future content work). Everything
is derived from the golden model so the RTL, the .svh program include, and
the expected class can never drift apart.

Outputs (in --outdir, default ../fpga/mem):
  img_rom.memh    3*32*32 int8 image bytes (address 0 upward)
  wgt_rom.memh    all layer weights, tap-major per output channel
  layer_prog.svh  PROG_NUM_LAYERS / PROG_DESC[] packed descriptors /
                  PROG_RESULT_BASE localparams (generated - do not edit)
  expected.txt    line 1: expected class index (argmax, first max wins)
                  line 2: the 4 int8 class scores (hex, two's complement)
"""

import argparse
import random

from golden_mac_model import DATA_W
from golden_conv_model import (K, FM_ADDR_W, WGT_ADDR_W, out_dim, pack_desc,
                               run_program)

DMIN, DMAX = -(1 << (DATA_W - 1)), (1 << (DATA_W - 1)) - 1
MAX_LAYERS = 6
RESULT_BASE = 8192


def build_program():
    """Same shape as the verified ml_cifar_shape_32x32 vector case."""
    descs = []
    dims, ch = 32, 3
    bases = [0, 8192]
    wb = 0
    for li, oc in enumerate([8, 8, 8, 8, 4]):
        descs.append(dict(img_w=dims, img_h=dims, in_ch=ch, out_ch=oc,
                          stride=2, pad=1, out_shift=9,
                          ifm_base=bases[li % 2], ofm_base=bases[(li + 1) % 2],
                          wgt_base=wb))
        wb += oc * ch * K * K
        dims = out_dim(dims, 1, 2)
        ch = oc
    assert descs[-1]["ofm_base"] == RESULT_BASE
    return descs, wb


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--outdir", default="../fpga/mem")
    p.add_argument("--seed", type=int, default=7)
    args = p.parse_args()
    rng = random.Random(args.seed)

    descs, wgt_len = build_program()
    img = [rng.randint(DMIN, DMAX) for _ in range(3 * 32 * 32)]
    wgt = [rng.randint(DMIN, DMAX) for _ in range(wgt_len)]

    with open(f"{args.outdir}/img_rom.memh", "w") as f:
        f.write("\n".join(format(v & 0xFF, "02x") for v in img) + "\n")
    with open(f"{args.outdir}/wgt_rom.memh", "w") as f:
        f.write("\n".join(format(v & 0xFF, "02x") for v in wgt) + "\n")

    with open(f"{args.outdir}/layer_prog.svh", "w") as f:
        f.write("// Generated by model/gen_fpga_mem.py (seed=%d) - DO NOT EDIT.\n"
                % args.seed)
        f.write("// Descriptor bit layout matches tinynpu_pkg::layer_desc_t and\n")
        f.write("// model/golden_conv_model.py pack_desc().\n")
        f.write("localparam int PROG_NUM_LAYERS  = %d;\n" % len(descs))
        f.write("localparam int PROG_RESULT_BASE = %d;\n" % RESULT_BASE)
        f.write("localparam logic [%d:0] PROG_DESC [%d] = '{\n"
                % (66, MAX_LAYERS))
        for i in range(MAX_LAYERS):
            v = pack_desc(descs[i]) if i < len(descs) else 0
            comma = "," if i < MAX_LAYERS - 1 else ""
            note = ("  // layer %d" % i) if i < len(descs) else "  // unused"
            f.write("  67'h%017x%s%s\n" % (v, comma, note))
        f.write("};\n")

    # Golden execution: expected class = argmax of the 4 result bytes
    fm = [0] * (1 << FM_ADDR_W)
    fm[0:len(img)] = img
    wm = [0] * (1 << WGT_ADDR_W)
    wm[0:len(wgt)] = wgt
    run_program(fm, wm, descs)
    scores = fm[RESULT_BASE:RESULT_BASE + 4]
    best = 0
    for i in range(1, 4):
        if scores[i] > scores[best]:  # strict >: first max wins, matches RTL
            best = i

    with open(f"{args.outdir}/expected.txt", "w") as f:
        f.write("%d\n" % best)
        f.write(" ".join(format(v & 0xFF, "02x") for v in scores) + "\n")

    print(f"program: {len(descs)} layers, {wgt_len} weight bytes")
    print(f"class scores (int8): {scores} -> expected class {best}")


if __name__ == "__main__":
    main()
