// -----------------------------------------------------------------------------
// TinyNPU top-level wrapper (Phase 7) — board-agnostic. A debounced button
// press runs one classification of the built-in demo image:
//
//   T_IDLE -> T_LOAD  copy the image ROM into the feature-map buffer
//          -> T_START pulse npu_core start (layer program from layer_prog.svh,
//                     generated by model/gen_fpga_mem.py from the golden model)
//          -> T_RUN   wait for npu_core done
//          -> T_READ  read the NUM_CLASSES result bytes, signed argmax
//                     (strict >, so the first maximum wins — matches golden)
//          -> T_SHOW  latch the class into the display stub, back to idle
//
// Memory ownership by state: T_LOAD owns the fm write port (from the image
// ROM), T_RUN hands both fm ports and the weight ROM to npu_core, T_READ owns
// the fm read port. Board specifics (pins, polarity) live in the board shim
// under fpga/<board>/ — nothing in here is board-specific.
// -----------------------------------------------------------------------------
module tinynpu_top #(
  parameter int    DEBOUNCE_CNT_W = 16,             // small override for sim
  parameter string IMG_INIT       = "img_rom.memh",
  parameter string WGT_INIT       = "wgt_rom.memh"
)(
  input  logic       clk,
  input  logic       rst_n,      // asynchronous, active-low (board shim provides)
  input  logic       btn_start,  // raw classify button, active-high
  output logic [3:0] led_class,  // one-hot classification result
  output logic       led_busy,
  output logic       led_sat
);

  import tinynpu_pkg::*;

  `include "layer_prog.svh"

  localparam int IMG_BYTES  = NUM_CHANNELS * IMG_WIDTH * IMG_HEIGHT;  // 3072
  localparam int IMG_ADDR_W = $clog2(IMG_BYTES);

  // ---------------------------------------------------------------------------
  // Reset synchronizer (async assert, synchronous release)
  // ---------------------------------------------------------------------------
  logic rst_n_meta, rst_n_sync;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rst_n_meta <= 1'b0;
      rst_n_sync <= 1'b0;
    end else begin
      rst_n_meta <= 1'b1;
      rst_n_sync <= rst_n_meta;
    end
  end

  // ---------------------------------------------------------------------------
  // Button
  // ---------------------------------------------------------------------------
  logic start_pressed;

  btn_debounce #(.CNT_W(DEBOUNCE_CNT_W)) u_btn (
    .clk     (clk),
    .rst_n   (rst_n_sync),
    .btn_in  (btn_start),
    .pressed (start_pressed)
  );

  // ---------------------------------------------------------------------------
  // Wrapper FSM
  // ---------------------------------------------------------------------------
  typedef enum logic [2:0] {
    T_IDLE  = 3'd0,
    T_LOAD  = 3'd1,
    T_START = 3'd2,
    T_RUN   = 3'd3,
    T_READ  = 3'd4,
    T_SHOW  = 3'd5
  } state_t;

  state_t state;

  // Image loader pipeline (1-cycle ROM latency)
  logic [IMG_ADDR_W-1:0] ld_cnt;
  logic                  ld_issue;      // reading img ROM this cycle
  logic                  ld_wr_v;       // ROM data valid -> fm write this cycle
  logic [IMG_ADDR_W-1:0] ld_wr_addr;

  // Result readout pipeline (1-cycle fm latency) and signed argmax
  logic [2:0]                cmp_issue_cnt;
  logic                      cmp_v;
  logic [2:0]                cmp_idx;
  logic signed [DATA_W-1:0]  best_val;
  logic [1:0]                best_idx;

  logic npu_start, npu_busy, npu_done, npu_sat;
  logic result_valid;

  assign ld_issue = (state == T_LOAD) && (32'(ld_cnt) < IMG_BYTES);

  always_ff @(posedge clk or negedge rst_n_sync) begin
    if (!rst_n_sync) begin
      state         <= T_IDLE;
      ld_cnt        <= '0;
      ld_wr_v       <= 1'b0;
      ld_wr_addr    <= '0;
      cmp_issue_cnt <= '0;
      cmp_v         <= 1'b0;
      cmp_idx       <= '0;
      best_val      <= '0;
      best_idx      <= '0;
      npu_start     <= 1'b0;
      result_valid  <= 1'b0;
    end else begin
      npu_start    <= 1'b0;
      result_valid <= 1'b0;

      // loader write pipeline (follows ld_issue by one cycle)
      ld_wr_v    <= ld_issue;
      ld_wr_addr <= ld_cnt;

      // readout compare pipeline
      cmp_v   <= (state == T_READ) && (32'(cmp_issue_cnt) < NUM_CLASSES);
      cmp_idx <= cmp_issue_cnt;

      unique case (state)
        T_IDLE: begin
          if (start_pressed) begin
            ld_cnt <= '0;
            state  <= T_LOAD;
          end
        end

        T_LOAD: begin
          if (ld_issue)
            ld_cnt <= ld_cnt + 1'b1;
          if (ld_wr_v && (32'(ld_wr_addr) == IMG_BYTES - 1)) begin
            npu_start <= 1'b1;
            state     <= T_START;
          end
        end

        T_START: begin
          state <= T_RUN;  // start pulse was driven on entry to this state
        end

        T_RUN: begin
          if (npu_done) begin
            cmp_issue_cnt <= '0;
            state         <= T_READ;
          end
        end

        T_READ: begin
          if (32'(cmp_issue_cnt) < NUM_CLASSES)
            cmp_issue_cnt <= cmp_issue_cnt + 1'b1;
          if (cmp_v) begin
            if (cmp_idx == 0 || $signed(fm_rdata) > best_val) begin
              best_val <= $signed(fm_rdata);
              best_idx <= cmp_idx[1:0];
            end
            if (32'(cmp_idx) == NUM_CLASSES - 1) begin
              result_valid <= 1'b1;
              state        <= T_SHOW;
            end
          end
        end

        T_SHOW: begin
          state <= T_IDLE;
        end

        default: state <= T_IDLE;
      endcase
    end
  end

  // ---------------------------------------------------------------------------
  // Layer program (generated include)
  // ---------------------------------------------------------------------------
  layer_desc_t [MAX_LAYERS-1:0] cfg_layers;

  for (genvar gi = 0; gi < MAX_LAYERS; gi++) begin : g_prog
    assign cfg_layers[gi] = layer_desc_t'(PROG_DESC[gi]);
  end

  // ---------------------------------------------------------------------------
  // Memories and port muxing
  // ---------------------------------------------------------------------------
  logic                  img_re;
  logic [IMG_ADDR_W-1:0] img_addr;
  logic [DATA_W-1:0]     img_rdata;

  logic                  npu_fm_re, npu_fm_wen;
  logic [FM_ADDR_W-1:0]  npu_fm_raddr, npu_fm_waddr;
  logic [DATA_W-1:0]     npu_fm_wdata;

  logic                  fm_re, fm_wen;
  logic [FM_ADDR_W-1:0]  fm_raddr, fm_waddr;
  logic [DATA_W-1:0]     fm_rdata, fm_wdata;

  logic                  wgt_re;
  logic [WGT_ADDR_W-1:0] wgt_addr;
  logic [DATA_W-1:0]     wgt_rdata;

  assign img_re   = ld_issue;
  assign img_addr = ld_cnt;

  assign fm_re    = (state == T_RUN) ? npu_fm_re
                  : ((state == T_READ) && (32'(cmp_issue_cnt) < NUM_CLASSES));
  assign fm_raddr = (state == T_RUN) ? npu_fm_raddr
                  : FM_ADDR_W'(PROG_RESULT_BASE + 32'(cmp_issue_cnt));

  assign fm_wen   = (state == T_LOAD) ? ld_wr_v
                  : ((state == T_RUN) ? npu_fm_wen : 1'b0);
  assign fm_waddr = (state == T_LOAD) ? FM_ADDR_W'(ld_wr_addr) : npu_fm_waddr;
  assign fm_wdata = (state == T_LOAD) ? img_rdata : npu_fm_wdata;

  byte_rom #(
    .ADDR_W    (IMG_ADDR_W),
    .DATA_W    (DATA_W),
    .INIT_FILE (IMG_INIT)
  ) u_img_rom (
    .clk   (clk),
    .re    (img_re),
    .addr  (img_addr),
    .rdata (img_rdata)
  );

  byte_rom #(
    .ADDR_W    (WGT_ADDR_W),
    .DATA_W    (DATA_W),
    .INIT_FILE (WGT_INIT)
  ) u_wgt_rom (
    .clk   (clk),
    .re    (wgt_re),
    .addr  (wgt_addr),
    .rdata (wgt_rdata)
  );

  fm_buffer u_fm (
    .clk   (clk),
    .re    (fm_re),
    .raddr (fm_raddr),
    .rdata (fm_rdata),
    .wen   (fm_wen),
    .waddr (fm_waddr),
    .wdata (fm_wdata)
  );

  // ---------------------------------------------------------------------------
  // NPU core
  // ---------------------------------------------------------------------------
  npu_core u_npu (
    .clk            (clk),
    .rst_n          (rst_n_sync),
    .cfg_layers     (cfg_layers),
    .cfg_num_layers (3'(PROG_NUM_LAYERS)),
    .start          (npu_start),
    .busy           (npu_busy),
    .done           (npu_done),
    .sat_seen       (npu_sat),
    .fm_re          (npu_fm_re),
    .fm_raddr       (npu_fm_raddr),
    .fm_rdata       (fm_rdata),
    .fm_wen         (npu_fm_wen),
    .fm_waddr       (npu_fm_waddr),
    .fm_wdata       (npu_fm_wdata),
    .wgt_re         (wgt_re),
    .wgt_addr       (wgt_addr),
    .wgt_rdata      (wgt_rdata)
  );

  // ---------------------------------------------------------------------------
  // Display
  // ---------------------------------------------------------------------------
  display_stub u_disp (
    .clk          (clk),
    .rst_n        (rst_n_sync),
    .result_valid (result_valid),
    .class_idx    (best_idx),
    .busy         (npu_busy || (state inside {T_LOAD, T_START, T_READ})),
    .sat          (npu_sat),
    .led_class    (led_class),
    .led_busy     (led_busy),
    .led_sat      (led_sat)
  );

endmodule : tinynpu_top
