// -----------------------------------------------------------------------------
// Random: constrained-random chained programs generated by the seeded Python
// model (vectors/npu/random_manifest.txt).
// -----------------------------------------------------------------------------
class npu_random_test extends npu_base_test;

  `uvm_component_utils(npu_random_test)

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void start_of_simulation_phase(uvm_phase phase);
    super.start_of_simulation_phase(phase);
    `uvm_info("NPU_TEST", "npu_random_test: expects the random suite manifest", UVM_LOW)
  endfunction

endclass : npu_random_test
