// Generated by model/gen_fpga_mem.py (seed=7) - DO NOT EDIT.
// Descriptor bit layout matches tinynpu_pkg::layer_desc_t and
// model/golden_conv_model.py pack_desc().
localparam int PROG_NUM_LAYERS  = 5;
localparam int PROG_RESULT_BASE = 8192;
localparam logic [66:0] PROG_DESC [6] = '{
  67'h4101c690002000000,  // layer 0
  67'h208446980000000d8,  // layer 1
  67'h10444690002000318,  // layer 2
  67'h08244698000000558,  // layer 3
  67'h04142690002000798,  // layer 4
  67'h00000000000000000  // unused
};
